//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.23 at 06:46:33 PM CET 
//


package com.sun.java.xml.ns.javaee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 
 *         Specifies the type of body that is valid for a tag.
 * 	This value is used by the JSP container to validate
 * 	that a tag invocation has the correct body syntax and
 * 	by page composition tools to assist the page author
 * 	in providing a valid tag body.
 * 
 * 	There are currently four values specified:
 * 
 * 	tagdependent    The body of the tag is interpreted by the tag
 * 			implementation itself, and is most likely
 * 			in a different "language", e.g embedded SQL
 * 			statements.
 * 
 * 	JSP             The body of the tag contains nested JSP
 * 			syntax.
 * 
 * 	empty           The body must be empty
 * 
 * 	scriptless      The body accepts only template text, EL
 * 			Expressions, and JSP action elements.  No
 * 			scripting elements are allowed.
 * 
 *       
 * 
 * <p>Java class for body-contentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="body-contentType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://java.sun.com/xml/ns/javaee>string">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "body-contentType")
public class BodyContentType
    extends String
{


}
