//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.23 at 06:46:33 PM CET 
//


package com.sun.java.xml.ns.javaee;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 
 * 	The variableType provides information on the scripting
 * 	variables defined by using this tag.  It is a (translation
 * 	time) error for a tag that has one or more variable
 * 	subelements to have a TagExtraInfo class that returns a
 * 	non-null value from a call to getVariableInfo().
 * 
 * 	The subelements of variableType are of the form:
 * 
 * 	description              Optional description of this
 * 				 variable
 * 
 * 	name-given               The variable name as a constant
 * 
 * 	name-from-attribute      The name of an attribute whose
 * 				 (translation time) value will
 * 				 give the name of the
 * 				 variable.  One of name-given or
 * 				 name-from-attribute is required.
 * 
 * 	variable-class           Name of the class of the variable.
 * 				 java.lang.String is default.
 * 
 * 	declare                  Whether the variable is declared
 * 				 or not.  True is the default.
 * 
 * 	scope                    The scope of the scripting varaible
 * 				 defined.  NESTED is default.
 * 
 *       
 * 
 * <p>Java class for variableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="variableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://java.sun.com/xml/ns/javaee}descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="name-given" type="{http://java.sun.com/xml/ns/javaee}java-identifierType"/>
 *           &lt;element name="name-from-attribute" type="{http://java.sun.com/xml/ns/javaee}java-identifierType"/>
 *         &lt;/choice>
 *         &lt;element name="variable-class" type="{http://java.sun.com/xml/ns/javaee}fully-qualified-classType" minOccurs="0"/>
 *         &lt;element name="declare" type="{http://java.sun.com/xml/ns/javaee}generic-booleanType" minOccurs="0"/>
 *         &lt;element name="scope" type="{http://java.sun.com/xml/ns/javaee}variable-scopeType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "variableType", propOrder = {
    "description",
    "nameGiven",
    "nameFromAttribute",
    "variableClass",
    "declare",
    "scope"
})
public class VariableType {

    protected List<DescriptionType> description;
    @XmlElement(name = "name-given")
    protected JavaIdentifierType nameGiven;
    @XmlElement(name = "name-from-attribute")
    protected JavaIdentifierType nameFromAttribute;
    @XmlElement(name = "variable-class")
    protected FullyQualifiedClassType variableClass;
    protected GenericBooleanType declare;
    protected VariableScopeType scope;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the nameGiven property.
     * 
     * @return
     *     possible object is
     *     {@link JavaIdentifierType }
     *     
     */
    public JavaIdentifierType getNameGiven() {
        return nameGiven;
    }

    /**
     * Sets the value of the nameGiven property.
     * 
     * @param value
     *     allowed object is
     *     {@link JavaIdentifierType }
     *     
     */
    public void setNameGiven(JavaIdentifierType value) {
        this.nameGiven = value;
    }

    /**
     * Gets the value of the nameFromAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link JavaIdentifierType }
     *     
     */
    public JavaIdentifierType getNameFromAttribute() {
        return nameFromAttribute;
    }

    /**
     * Sets the value of the nameFromAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link JavaIdentifierType }
     *     
     */
    public void setNameFromAttribute(JavaIdentifierType value) {
        this.nameFromAttribute = value;
    }

    /**
     * Gets the value of the variableClass property.
     * 
     * @return
     *     possible object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public FullyQualifiedClassType getVariableClass() {
        return variableClass;
    }

    /**
     * Sets the value of the variableClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public void setVariableClass(FullyQualifiedClassType value) {
        this.variableClass = value;
    }

    /**
     * Gets the value of the declare property.
     * 
     * @return
     *     possible object is
     *     {@link GenericBooleanType }
     *     
     */
    public GenericBooleanType getDeclare() {
        return declare;
    }

    /**
     * Sets the value of the declare property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericBooleanType }
     *     
     */
    public void setDeclare(GenericBooleanType value) {
        this.declare = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link VariableScopeType }
     *     
     */
    public VariableScopeType getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableScopeType }
     *     
     */
    public void setScope(VariableScopeType value) {
        this.scope = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
